version: 2 # use CircleCI 2.0
jobs:
  build:
    parallelism: 1
    docker:
      - image: cimg/ruby:2.7
        environment:
          EXAMPLE: 3
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: gem install bundler && bundle -v
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Validate HTML
          command: ./ci.sh
